<?php /* This is a PHP data file */ if (!@$LOADSTRUCT) { die("This is not a program file."); }
return array (
  '_detailPage' => '',
  '_disableAdd' => '0',
  '_disableErase' => '0',
  '_disableModify' => '0',
  '_disablePreview' => '0',
  '_disableView' => '0',
  '_filenameFields' => '',
  '_hideRecordsFromDisabledAccounts' => '0',
  '_indent' => NULL,
  '_listPage' => '',
  '_maxRecords' => '',
  '_maxRecordsPerUser' => '',
  '_perPageDefault' => '25',
  '_previewPage' => '',
  '_requiredPlugins' => '',
  '_tableName' => 'commercial_hub_landing_pages',
  'listPageFields' => NULL,
  'listPageOrder' => '',
  'listPageSearchFields' => '',
  'menuHidden' => '0',
  'menuName' => 'Landing Pages',
  'menuOrder' => '0000000377',
  'menuType' => 'menugroup',
);
?>